#!/bin/sh
set -eu

account_ids="${1:-${CLAUDE_WORKER_ACCOUNT_IDS:-}}"
output="${2:-deploy/docker-compose.claude-workers.yml}"

if [ -z "${account_ids}" ]; then
  echo "usage: $0 ACCOUNT_ID[,ACCOUNT_ID...] [OUTPUT_FILE]" >&2
  exit 2
fi

mapping=""
services=""
seen=","
old_ifs="${IFS}"
IFS=','
for raw_id in ${account_ids}; do
  account_id=$(printf '%s' "${raw_id}" | tr -d '[:space:]')
  case "${account_id}" in
    ''|*[!0-9]*|0)
      echo "invalid Claude account ID: ${raw_id}" >&2
      exit 2
      ;;
  esac
  case "${seen}" in
    *",${account_id},"*)
      echo "duplicate Claude account ID: ${account_id}" >&2
      exit 2
      ;;
  esac
  seen="${seen}${account_id},"
  endpoint="${account_id}=http://claude-worker-${account_id}:8090"
  if [ -n "${mapping}" ]; then
    mapping="${mapping},${endpoint}"
  else
    mapping="${endpoint}"
  fi
  services="${services} ${account_id}"
done
IFS="${old_ifs}"

tmp="${output}.tmp"
mkdir -p "$(dirname "${output}")"
{
  echo "# Generated by deploy/generate-claude-workers.sh. Do not store secrets here."
  echo "services:"
  echo "  app:"
  echo "    environment:"
  printf '      - CLAUDE_ACCOUNT_WORKERS=%s\n' "${mapping}"
  echo '      - CLAUDE_WORKER_SHARED_SECRET=${CLAUDE_WORKER_SHARED_SECRET:?CLAUDE_WORKER_SHARED_SECRET is required}'

  for account_id in ${services}; do
    printf '  claude-worker-%s:\n' "${account_id}"
    echo '    image: ${APP_IMAGE:-ghcr.io/olibazeva363-ops/haochi:latest}'
    printf '    container_name: tokenhub-claude-worker-%s\n' "${account_id}"
    echo '    restart: unless-stopped'
    echo '    labels:'
    echo '      - com.centurylinklabs.watchtower.enable=true'
    echo '    environment:'
    printf '      - CLAUDE_ACCOUNT_WORKER_ID=%s\n' "${account_id}"
    echo '      - CLAUDE_ACCOUNT_WORKER_LISTEN=0.0.0.0:8090'
    echo '      - CLAUDE_WORKER_SHARED_SECRET=${CLAUDE_WORKER_SHARED_SECRET:?CLAUDE_WORKER_SHARED_SECRET is required}'
    echo '      - SERVER_PORT=8090'
    echo '      - SERVER_MODE=release'
    echo '      - TZ=${TZ:-Asia/Shanghai}'
    echo '    volumes:'
    printf '      - ./claude_worker_data/%s:/app/data\n' "${account_id}"
    echo '    tmpfs:'
    echo '      - /tmp'
    echo '    networks: [tokenhub]'
    echo '    healthcheck:'
    echo '      test: ["CMD", "wget", "-q", "-T", "5", "-O", "/dev/null", "http://localhost:8090/health"]'
    echo '      interval: 15s'
    echo '      timeout: 5s'
    echo '      retries: 3'
    echo '      start_period: 10s'
  done
} > "${tmp}"
mv "${tmp}" "${output}"
printf 'generated %s for accounts:%s\n' "${output}" "${services}"
